name = "clawfirm"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "clawfirm-auth"
database_id = "a1d58845-021b-436a-ae9c-ecf1d0af03c5"

[[kv_namespaces]]
binding = "WHIPS"
id = "bdc3f8b401944e9d96aa47b932ea44b9"

